{% set name = "awslimitchecker" %}
{% set version = "11.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08e53145f44c6689076de7b98ba5fd40b654f11cf2724ef46db17a1df9c78af9

build:
  entry_points:
    - awslimitchecker = awslimitchecker.runner:console_entry_point
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - boto3 >=1.9.175
    - botocore
    - python >=3.5
    - python-dateutil
    - pytz
    - termcolor >=1.1.0
    - urllib3
    - versionfinder >=0.1.1

test:
  imports:
    - awslimitchecker
    - awslimitchecker.alerts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jantman/awslimitchecker
  summary: A script and python module to check your AWS service limits and usage, and warn when usage approaches limits.
  license: AGPL-3.0-only
  license_file: LICENSE
  doc_url: https://github.com/jantman/awslimitchecker
  dev_url: https://github.com/jantman/awslimitchecker

extra:
  recipe-maintainers:
    - BastianZim
    - jantman
