{% set name = "awslimitchecker" %}
{% set version = "12.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: adfd2bb2b971609a5ef35a50a037336ca82e9fd64ae6a25a0647c7bb802d9a65

build:
  entry_points:
    - awslimitchecker = awslimitchecker.runner:console_entry_point
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - boto3 >=1.9.175
    - botocore
    - python >={{ python_min }}
    - python-dateutil
    - pytz
    - termcolor >=1.1.0
    - urllib3
    - versionfinder >=0.1.1

test:
  imports:
    - awslimitchecker
    - awslimitchecker.alerts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jantman/awslimitchecker
  summary: A script and python module to check your AWS service limits and usage, and warn when usage approaches limits.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://github.com/jantman/awslimitchecker
  dev_url: https://github.com/jantman/awslimitchecker

extra:
  recipe-maintainers:
    - BastianZim
    - jantman
